#! /bin/bash

NETMASK_HEX=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f4 | cut -c 3-)
IP_DEC=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2)

FRST_MSK_OCT=$(echo $NETMASK_HEX | cut -c 1-2 | tr a-z A-Z)
SCND_MSK_OCT=$(echo $NETMASK_HEX | cut -c 3-4 | tr a-z A-Z)
THRD_MSK_OCT=$(echo $NETMASK_HEX | cut -c 5-6 | tr a-z A-Z)
FRTH_MSK_OCT=$(echo $NETMASK_HEX | cut -c 7-8 | tr a-z A-Z)

FRST_IP_OCT=$(echo $IP_DEC | cut -d. -f1)
SCND_IP_OCT=$(echo $IP_DEC | cut -d. -f2)
THRD_IP_OCT=$(echo $IP_DEC | cut -d. -f3)
FRTH_IP_OCT=$(echo $IP_DEC | cut -d. -f4)

FRST_MSK_OCT=$(echo "ibase=16; $FRST_MSK_OCT" | bc)
SCND_MSK_OCT=$(echo "ibase=16; $SCND_MSK_OCT" | bc)
THRD_MSK_OCT=$(echo "ibase=16; $THRD_MSK_OCT" | bc)
FRTH_MSK_OCT=$(echo "ibase=16; $FRTH_MSK_OCT" | bc)


function c_sub {
if [ $1 -eq 255 ]
then
	RES=$2
fi

if [ $1 -eq 0 ]
then
	RES=0
fi	

if [ $1 -ne 255 -a $1 -ne 0 ]
then
	RES=$(($1 & $2)) 
fi
echo $RES
}

SBN_OCT_1=$(c_sub $FRST_MSK_OCT $FRST_IP_OCT)
SBN_OCT_2=$(c_sub $SCND_MSK_OCT $SCND_IP_OCT)
SBN_OCT_3=$(c_sub $THRD_MSK_OCT $THRD_IP_OCT)
SBN_OCT_4=$(c_sub $FRTH_MSK_OCT $FRTH_IP_OCT)

function c_bcast {

if [ $1 -eq 255 ]
then
	RES=$2
fi

if [ $1 -eq 0 ]
then
	RES=255
fi	

if [ $1 -ne 255 -a $1 -ne 0 ];
then
	RES=$(($1 ^ 255))
    RES=$(($RES | $2))	
fi
echo $RES
}

BC_1=$(c_bcast $FRST_MSK_OCT $FRST_IP_OCT)
BC_2=$(c_bcast $SCND_MSK_OCT $SCND_IP_OCT)
BC_3=$(c_bcast $THRD_MSK_OCT $THRD_IP_OCT)
BC_4=$(c_bcast $FRTH_MSK_OCT $FRTH_IP_OCT)

function c_noh {
RES=$(($FRST_MSK_OCT ^ 255))
RES=$(($RES | $(($RES<<32))))

RES=$(($SCND_MSK_OCT ^ 255))
RES=$(($RES | $(($RES<<16))))

RES=$(($THRD_MSK_OCT ^ 255))
RES=$(($RES | $(($RES<<8))))


RES=$(($RES | $(($FRTH_MSK_OCT ^ 255))))

echo $RES
}

echo "ip        = $FRST_IP_OCT.$SCND_IP_OCT.$THRD_IP_OCT.$FRTH_IP_OCT"
echo "netmask   = $FRST_MSK_OCT.$SCND_MSK_OCT.$THRD_MSK_OCT.$FRTH_MSK_OCT"
echo "subnet    = $SBN_OCT_1.$SBN_OCT_2.$SBN_OCT_3.$SBN_OCT_4"
echo "broadcast = $BC_1.$BC_2.$BC_3.$BC_4"
echo "number of ip = $(c_noh)"
