#!/bin/env bash

USAGE='usage: ./02 [username] [kick/dell]'
E_OPTERROR=65

if [ $# -ne 2 ]
then
        echo $USAGE
        echo
        exit $E_OPTERROR
fi

if [ $2 == "del" ]
then
        echo "we are going to kick user $1 and delete him from system"
fi

if [ $2 == "kick" ]
then
        echo "we are going to kick user $1 and nothing more"
fi

if [ $2 != "kick" -a $2 != "del" ]
then
        echo $USAGE
        echo
        exit $E_OPTERROR
fi

ONLINE_USER=$(who | awk NR\ ==\ 1\{print\ \$1\})
COUNTER=1

until [ -z $ONLINE_USER ]; do
        ONLINE_USER=$(who | awk NR\ ==\ $COUNTER\{print\ \$1\})


if [[ "$ONLINE_USER" = "$1" && "$2" = "del" ]]
then
        echo "we found $1 and will remove it !!!"
        killall -u $ONLINE_USER
        userdel -r $ONLINE_USER
fi

if [[ "$ONLINE_USER" = "$1" && "$2" = "kick" ]]
then
        echo "we found $1 and will kick it !!!"
        killall -u $ONLINE_USER
fi
        let COUNTER+=1
done

echo